local M = {}

local disabled_plugins = {
  -- "bigfile.nvim",
  "cmp-buffer",
  "cmp-nvim-lsp",
  "cmp-path",
  "cmp_luasnip",
  -- "dark-notify",
  "dashboard-nvim",
  "diffview.nvim",
  -- "flash.nvim",
  "follow-md-links.nvim",
  "friendly-snippets",
  "fugitive-gitlab.vim",
  -- "fzf-lua",
  "gitsigns.nvim",
  "hbac.nvim",
  "indent-blankline.nvim",
  -- "lazy.nvim",
  -- "LazyVim",
  -- "log-highlight.nvim",
  -- "lualine.nvim",
  "LuaSnip",
  "mason-lspconfig.nvim",
  "mason.nvim",
  "mini.ai",
  "mini.comment",
  "mini.indentscope",
  "mini.pairs",
  "neo-tree.nvim",
  "neoconf.nvim",
  "neodev.nvim",
  "neogit",
  -- "noice.nvim",
  -- "nui.nvim",
  "nvim-cmp",
  -- "nvim-colorizer.lua",
  "nvim-lint",
  "nvim-lsp-file-operations",
  "nvim-lspconfig",
  -- "nvim-notify",
  -- "nvim-scrollbar",
  -- "nvim-treesitter",
  -- "nvim-treesitter-context",
  -- "nvim-treesitter-textobjects",
  "nvim-ts-autotag",
  -- "nvim-ufo",
  -- "nvim-web-devicons",
  -- "onedark.nvim",
  "persistence.nvim",
  -- "plenary.nvim",
  -- "promise-async",
  "smart-open.nvim",
  -- "sqlite.lua",
  -- "telescope-fzf-native.nvim",
  -- "telescope-zf-native.nvim",
  -- "telescope.nvim",
  -- "text-case.nvim",
  -- "todo-comments.nvim",
  -- "trouble.nvim",
  -- "vim-fugitive",
  -- "vim-illuminate",
  -- "which-key.nvim",
  "window-picker",
}

for _, plugin in ipairs(disabled_plugins) do
  table.insert(M, { plugin, enabled = false })
end

return M
